import{db,$,clean,escapeHtml,normalizeSpeech,sessionCode,loadCatalog,commandPayload,createPresentationChannel,presenceHasRole,sendBroadcast,requireSession}from"../shared/core.js";
const state={menus:[],contents:[],recent:[],channel:null,code:"",pending:new Map(),display:false};
let toastTimer;
function toast(text){clearTimeout(toastTimer);$("toast").textContent=text;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),2400)}
function makeButton(item){return `<button class="command-button" data-content="${item.id}"><b>${item.is_favorite?"★ ":""}${escapeHtml(item.button_label||item.title)}</b><small>${escapeHtml(item.title)}</small></button>`}
function render(filter=""){
 const q=clean(filter).toLowerCase();const items=state.contents.filter(c=>!q||[c.title,c.button_label,c.voice_command,...(c.voice_aliases||[]),...(c.keywords||[])].join(" ").toLowerCase().includes(q));
 $("favorites").innerHTML=state.contents.filter(c=>c.is_favorite).slice(0,10).map(makeButton).join("")||'<div class="empty">즐겨찾기가 없습니다.</div>';
 $("catalog").innerHTML=state.menus.map(menu=>{const children=items.filter(c=>c.menu_id===menu.id);return children.length?`<details class="panel menu" open><summary>${escapeHtml(menu.title)}</summary><div class="menu-grid">${children.map(makeButton).join("")}</div></details>`:""}).join("")+(q&&!items.length?'<div class="panel empty">검색 결과가 없습니다.</div>':"");
 $("recent").innerHTML=state.recent.map(id=>state.contents.find(c=>c.id===id)).filter(Boolean).map(makeButton).join("")||'<div class="empty">아직 사용한 자료가 없습니다.</div>';
 document.querySelectorAll("[data-content]").forEach(button=>button.onclick=()=>showContent(button.dataset.content,"touch"));
}
async function showContent(id,source){const item=state.contents.find(c=>c.id===id);if(!item)return;if(!state.display){toast("⚠ DISPLAY 연결을 확인하세요");return}const payload=commandPayload(item,source);state.pending.set(payload.id,setTimeout(()=>{state.pending.delete(payload.id);toast("⚠ 화면 연결을 확인하세요")},AI_OFFICE_CONFIG.commandTimeoutMs));toast("전송 중…");await sendBroadcast(state.channel,"command",payload);state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,8);localStorage.setItem("aiOfficeRecent",JSON.stringify(state.recent));render($("searchInput").value)}
function connect(code){if(state.channel)db.removeChannel(state.channel);state.code=code;localStorage.setItem("aiOfficeSessionCode",code);$("codeTitle").textContent=`연결코드 · ${code}`;$("sessionText").textContent=`SESSION ${code}`;state.channel=createPresentationChannel(code,"control",{presence:p=>{state.display=presenceHasRole(p,"display");$("displayDot").classList.toggle("on",state.display);$("displayStatus").textContent=state.display?"DISPLAY 연결됨":"DISPLAY 연결 대기"},ack:p=>{const timer=state.pending.get(p.commandId);if(timer){clearTimeout(timer);state.pending.delete(p.commandId)}toast(p.ok?"✓ 표시 완료":`⚠ ${p.message||"표시 실패"}`)}})}
function startVoice(){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){toast("이 브라우저는 음성인식을 지원하지 않습니다.");return}const r=new SpeechRecognition();r.lang="ko-KR";r.interimResults=false;r.maxAlternatives=3;$("ptt").classList.add("listening");$("ptt").querySelector("span").textContent="듣고 있습니다";r.onresult=e=>{const phrases=Array.from(e.results[0]).map(x=>x.transcript);const normalized=phrases.map(normalizeSpeech);const match=state.contents.find(c=>[c.voice_command,...(c.voice_aliases||[]),c.title,c.button_label].filter(Boolean).some(a=>normalized.some(p=>p.includes(normalizeSpeech(a))||normalizeSpeech(a).includes(p))));if(match){toast(`“${phrases[0]}” → ${match.title}`);showContent(match.id,"voice")}else toast(`명령을 찾지 못했습니다: ${phrases[0]}`)};r.onerror=()=>toast("음성을 인식하지 못했습니다.");r.onend=()=>{$("ptt").classList.remove("listening");$("ptt").querySelector("span").textContent="눌러서 말하기"};r.start()}
async function refreshCatalog(){Object.assign(state,await loadCatalog());render($("searchInput").value)}
async function boot(){if(!await requireSession("../"))return;state.recent=JSON.parse(localStorage.getItem("aiOfficeRecent")||"[]");try{await refreshCatalog()}catch(e){toast("자료를 불러오지 못했습니다. 설치 SQL을 확인하세요.")}connect(localStorage.getItem("aiOfficeSessionCode")||sessionCode());db.channel("ai-office-catalog-control").on("postgres_changes",{event:"*",schema:"public",table:"ai_office_menus"},refreshCatalog).on("postgres_changes",{event:"*",schema:"public",table:"ai_office_contents"},refreshCatalog).subscribe();$("searchInput").oninput=e=>render(e.target.value);$("newSession").onclick=()=>connect(sessionCode());$("ptt").onclick=startVoice}boot();
