import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SINGLE_OWNER_EMAIL="jeonseongkweon@gmail.com";
const isSingleOwner=session=>String(session?.user?.email||"").trim().toLowerCase()===SINGLE_OWNER_EMAIL;
const cfg=window.KMT_STAR_CONFIG,db=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,detectSessionInUrl:true,flowType:"pkce"}}),$=id=>document.getElementById(id);
const state={periods:[],students:[],session:null,period:null,categories:[],category:null,attendance:[],events:[],praises:[],champions:[],realtimeChannel:null,realtimeTimer:null};
const praisePresets=["오늘 인사가 아주 좋았어요.","친구를 도와줬어요.","끝까지 포기하지 않았어요.","수업에 집중했어요."];
const clean=v=>v==null?"":String(v).trim(),escapeHtml=v=>clean(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function localDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:cfg.timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function localTime(v=new Date()){return new Intl.DateTimeFormat("ko-KR",{timeZone:cfg.timezone,hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(v))}
function toast(m){$("toast").textContent=m;$("toast").classList.add("show");clearTimeout(window.__t);window.__t=setTimeout(()=>$("toast").classList.remove("show"),1600)}
function enrollment(s){return Array.isArray(s.enrollments)?(s.enrollments[0]||{}):(s.enrollments||{})}
function rosterFor(p){return state.students.filter(s=>enrollment(s).class_period_id===p.id)}
function attendedStudents(){const ids=new Set(state.attendance.filter(a=>["present","late"].includes(a.status)).map(a=>a.student_id));return rosterFor(state.period).filter(s=>ids.has(s.id))}
function eventsFor(id){return state.events.filter(e=>e.student_id===id)}
function categoryCount(id,cat){return eventsFor(id).filter(e=>e.category_id===cat).length}

async function login(){const {error}=await db.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}${location.pathname}`,queryParams:{prompt:"select_account"}}});if(error)$("loginMessage").textContent=error.message}
async function boot(){const {data:{session}}=await db.auth.getSession();if(!session){$("loginScreen").hidden=false;return}if(!isSingleOwner(session)){$("loginMessage").textContent="이 화면을 사용할 지도자 권한이 없습니다.";return}$("loginScreen").hidden=true;$("app").hidden=false;startClock();await loadBase()}
function startClock(){const tick=()=>{$("dateLabel").textContent=new Intl.DateTimeFormat("ko-KR",{timeZone:cfg.timezone,year:"numeric",month:"long",day:"numeric",weekday:"short"}).format(new Date());$("clockLabel").textContent=localTime()};tick();setInterval(tick,15000)}
async function loadBase(){const [p,s,c]=await Promise.all([db.from("class_periods").select("*").eq("is_active",true).order("sort_order"),db.from("students").select("id,student_code,name,photo_url,enrollments(class_period_id,status)").order("student_code"),db.from("star_categories").select("*").eq("is_active",true).order("sort_order")]);const error=p.error||s.error||c.error;if(error){toast(error.message);return}state.periods=p.data||[];state.students=(s.data||[]).filter(x=>enrollment(x).status==="재원");state.categories=c.data||[];state.category=state.categories[0]||null;renderPeriods()}
function renderPeriods(){$("periodGrid").innerHTML=state.periods.map(p=>`<button class="period-card" data-id="${p.id}"><small>${escapeHtml(p.code)}</small><strong>${escapeHtml(p.name)}</strong><span>${rosterFor(p).length}명 · STAR 수업판</span></button>`).join("");document.querySelectorAll(".period-card").forEach(b=>b.onclick=()=>openPeriod(state.periods.find(p=>p.id===b.dataset.id)))}
async function openPeriod(p){state.period=p;const {data,error}=await db.from("class_sessions").select("*").eq("session_date",localDate()).eq("class_period_id",p.id).maybeSingle();if(error){toast(error.message);return}if(!data){toast("먼저 출석 화면에서 오늘 수업을 시작해 주세요.");return}state.session=data;await loadRecords();startRealtime();$("periodScreen").hidden=true;$("starScreen").hidden=false;$("sessionDate").textContent=localDate();$("sessionTitle").textContent=`${p.name} STAR 수업`;renderCategories();renderStudents()}
async function loadRecords(){const [a,e,p,c]=await Promise.all([db.from("attendance").select("student_id,status").eq("session_id",state.session.id),db.from("star_events").select("*").eq("session_id",state.session.id).order("awarded_at"),db.from("praise_events").select("*").eq("session_id",state.session.id).order("praised_at"),db.from("champions").select("*,star_categories(name,icon)").eq("session_id",state.session.id).order("selected_at")]);const error=a.error||e.error||p.error||c.error;if(error){toast(error.message);return}state.attendance=a.data||[];state.events=e.data||[];state.praises=p.data||[];state.champions=c.data||[]}
function renderCategories(){$("categoryBar").innerHTML=state.categories.map(c=>`<button class="category ${c.id===state.category?.id?"active":""}" data-id="${c.id}">${c.icon} ${escapeHtml(c.name)}</button>`).join("");document.querySelectorAll(".category").forEach(b=>b.onclick=()=>{state.category=state.categories.find(c=>c.id===b.dataset.id);$("categoryName").textContent=`${state.category.icon} ${state.category.name} 선택됨`;renderCategories()})}
function renderStudents(){const list=attendedStudents();$("emptyMessage").hidden=!!list.length;$("totalStars").textContent=state.events.length;$("studentGrid").innerHTML=list.map(s=>{const count=eventsFor(s.id).length,photo=clean(s.photo_url),perfect=count>=cfg.perfectStar;return `<article class="student ${perfect?"perfect":""}"><button class="star-main" data-star="${s.id}">${photo?`<img class="photo" src="${escapeHtml(photo)}" alt="">`:`<div class="photo fallback">${escapeHtml(s.name.slice(0,2))}</div>`}<h2>${escapeHtml(s.name)}</h2><div class="star-count">⭐ × ${count}</div><div class="meter"><i style="width:${Math.min(100,count/cfg.perfectStar*100)}%"></i></div><small>${perfect?"PERFECT STAR":"카드를 눌러 +1"}</small></button><div class="card-actions"><button data-detail="${s.id}">상세</button><button class="praise" data-praise="${s.id}">👏 칭찬</button><button class="undo" data-undo="${s.id}">UNDO</button></div></article>`}).join("");document.querySelectorAll("[data-star]").forEach(b=>b.onclick=()=>award(state.students.find(s=>s.id===b.dataset.star)));document.querySelectorAll("[data-undo]").forEach(b=>b.onclick=()=>undo(state.students.find(s=>s.id===b.dataset.undo)));document.querySelectorAll("[data-detail]").forEach(b=>b.onclick=()=>showDetail(state.students.find(s=>s.id===b.dataset.detail)));document.querySelectorAll("[data-praise]").forEach(b=>b.onclick=()=>showPraise(state.students.find(s=>s.id===b.dataset.praise)))}
async function award(s){if(!state.category){toast("STAR 카테고리를 먼저 선택해 주세요.");return}if(state.session.status==="closed"){toast("종료된 수업입니다.");return}$("saveStatus").textContent=`${s.name} 저장 중...`;const {data,error}=await db.from("star_events").insert({session_id:state.session.id,student_id:s.id,category_id:state.category.id}).select().single();if(error){toast(error.message);return}state.events.push(data);renderStudents();showBurst(s,state.category,eventsFor(s.id).length);$("saveStatus").textContent="저장 완료";setTimeout(()=>$("saveStatus").textContent="Supabase 자동저장",800)}
function stopRealtime(){if(state.realtimeTimer){clearTimeout(state.realtimeTimer);state.realtimeTimer=null}if(state.realtimeChannel){db.removeChannel(state.realtimeChannel);state.realtimeChannel=null}}
function scheduleRealtimeRefresh(){clearTimeout(state.realtimeTimer);state.realtimeTimer=setTimeout(async()=>{if(!state.session)return;await loadRecords();renderStudents();if(!$("championDialog").open)renderChampions();$("saveStatus").textContent="Supabase 자동저장 · LIVE"},250)}
async function syncSessionState(){if(!state.session)return;const{data,error}=await db.from("class_sessions").select("*").eq("id",state.session.id).maybeSingle();if(!error&&data)state.session=data}
function startRealtime(){
  stopRealtime();if(!state.session)return;const sid=state.session.id;
  state.realtimeChannel=db.channel(`kmt-star-live-${sid}`)
    .on("postgres_changes",{event:"*",schema:"public",table:"attendance",filter:`session_id=eq.${sid}`},scheduleRealtimeRefresh)
    .on("postgres_changes",{event:"*",schema:"public",table:"star_events",filter:`session_id=eq.${sid}`},scheduleRealtimeRefresh)
    .on("postgres_changes",{event:"*",schema:"public",table:"praise_events",filter:`session_id=eq.${sid}`},scheduleRealtimeRefresh)
    .on("postgres_changes",{event:"*",schema:"public",table:"champions",filter:`session_id=eq.${sid}`},scheduleRealtimeRefresh)
    .on("postgres_changes",{event:"UPDATE",schema:"public",table:"class_sessions",filter:`id=eq.${sid}`},async()=>{await syncSessionState();scheduleRealtimeRefresh()})
    .subscribe(status=>{if(status==="SUBSCRIBED")$("saveStatus").textContent="Supabase 자동저장 · LIVE";else if(status==="CHANNEL_ERROR"||status==="TIMED_OUT")$("saveStatus").textContent="LIVE 재연결 중"});
}

function showBurst(s,c,total){$("burstIcon").textContent=c.icon;$("burstName").textContent=s.name;$("burstCategory").textContent=`${c.name} 획득!`;$("burstTotal").textContent=total>=cfg.perfectStar?`오늘 ⭐${total} · PERFECT STAR!`:`오늘 ⭐${total}`;$("starBurst").hidden=false;clearTimeout(window.__burst);window.__burst=setTimeout(()=>$("starBurst").hidden=true,total>=cfg.perfectStar?2400:1000)}
async function undo(s){const last=eventsFor(s.id).at(-1);if(!last){toast("되돌릴 STAR가 없습니다.");return}const {error}=await db.from("star_events").delete().eq("id",last.id);if(error){toast(error.message);return}state.events=state.events.filter(e=>e.id!==last.id);renderStudents();toast(`${s.name} 마지막 STAR 입력을 취소했습니다.`)}
function showDetail(s){const rows=state.categories.filter(c=>categoryCount(s.id,c.id)).map(c=>`<div class="detail-row"><span>${c.icon} ${escapeHtml(c.name)}</span><strong>${categoryCount(s.id,c.id)}</strong></div>`).join("");const praises=state.praises.filter(p=>p.student_id===s.id).map(p=>`<div class="detail-row"><span>👏 ${escapeHtml(p.message)}</span><small>${localTime(p.praised_at)}</small></div>`).join("");$("detailContent").innerHTML=`<h2>${escapeHtml(s.name)} · ⭐ × ${eventsFor(s.id).length}</h2>${rows||'<p class="muted">아직 받은 STAR가 없습니다.</p>'}<h3>오늘의 칭찬</h3>${praises||'<p class="muted">아직 칭찬 기록이 없습니다.</p>'}`;$("detailDialog").showModal()}
function showPraise(s){$("praiseStudentId").value=s.id;$("praiseTitle").textContent=`${s.name} 칭찬 기록`;$("praiseMessage").value="";$("praisePresets").innerHTML=praisePresets.map(x=>`<button type="button">${x}</button>`).join("");$("praisePresets").querySelectorAll("button").forEach(b=>b.onclick=()=>$("praiseMessage").value=b.textContent);$("praiseDialog").showModal()}
async function savePraise(e){e.preventDefault();const student_id=$("praiseStudentId").value,message=clean($("praiseMessage").value);const {data,error}=await db.from("praise_events").insert({session_id:state.session.id,student_id,message}).select().single();if(error){toast(error.message);return}state.praises.push(data);$("praiseDialog").close();toast("칭찬을 저장했습니다.")}
function championTitle(c){const map={GREETING:"인사왕",POSTURE:"집중왕",KICK:"발차기왕",CARE:"배려왕",CLEANUP:"정리왕",CHALLENGE:"도전왕",GAME:"게임왕",NEAT:"단정왕"};return map[c.code]||`${c.name} 왕`}
function showChampions(){const students=attendedStudents(),top=[...students].sort((a,b)=>eventsFor(b.id).length-eventsFor(a.id).length)[0];$("championSuggestions").innerHTML=`<div class="suggestion"><strong>🏆 오늘의 챔피언</strong><select data-title="오늘의 챔피언"><option value="">학생 선택</option>${students.map(s=>`<option value="${s.id}" ${s.id===top?.id?"selected":""}>${escapeHtml(s.name)} · ⭐${eventsFor(s.id).length}</option>`).join("")}</select><button>저장</button></div>`+state.categories.map(c=>{const rank=[...students].sort((a,b)=>categoryCount(b.id,c.id)-categoryCount(a.id,c.id))[0],score=rank?categoryCount(rank.id,c.id):0;return `<div class="suggestion"><strong>${c.icon} ${championTitle(c)}</strong><select data-title="${championTitle(c)}" data-category="${c.id}"><option value="">학생 선택</option>${students.map(s=>`<option value="${s.id}" ${score&&s.id===rank.id?"selected":""}>${escapeHtml(s.name)} · ${categoryCount(s.id,c.id)}</option>`).join("")}</select><button>저장</button></div>`}).join("");$("championSuggestions").querySelectorAll("button").forEach(b=>b.onclick=()=>saveChampion(b.previousElementSibling));renderChampions();$("championDialog").showModal()}
async function saveChampion(sel){if(!sel.value){toast("학생을 선택해 주세요.");return}const payload={session_id:state.session.id,student_id:sel.value,title:sel.dataset.title,category_id:sel.dataset.category||null};const {data,error}=await db.from("champions").upsert(payload,{onConflict:"session_id,title"}).select("*,star_categories(name,icon)").single();if(error){toast(error.message);return}state.champions=state.champions.filter(c=>c.title!==data.title);state.champions.push(data);renderChampions();toast(`${data.title} 저장 완료`)}
function renderChampions(){$("championList").innerHTML=state.champions.length?state.champions.map(c=>{const s=state.students.find(x=>x.id===c.student_id);return `<div class="champion-row"><span>${c.star_categories?.icon||"🏆"} ${escapeHtml(c.title)}</span><strong>${escapeHtml(s?.name||"")}</strong><button data-delete="${c.id}">삭제</button></div>`}).join(""):'<p class="muted">아직 선정된 챔피언이 없습니다.</p>';document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteChampion(b.dataset.delete))}
async function deleteChampion(id){const {error}=await db.from("champions").delete().eq("id",id);if(error){toast(error.message);return}state.champions=state.champions.filter(c=>c.id!==id);renderChampions()}

$("loginButton").onclick=login;$("logoutButton").onclick=async()=>{await db.auth.signOut();location.reload()};$("backButton").onclick=()=>{stopRealtime();$("starScreen").hidden=true;$("periodScreen").hidden=false;state.session=null;state.period=null};$("praiseForm").onsubmit=savePraise;$("championButton").onclick=showChampions;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());$("starBurst").onclick=()=>$("starBurst").hidden=true;db.auth.onAuthStateChange((_e,s)=>{if(s&&$("app").hidden)setTimeout(boot,0)});boot();
