const today=new Date('2026-09-10T09:00:00+09:00');
const demoHouseholds=[
{id:'h1',name:'김민규 · 김나라',students:['김민규','김나라'],parents:['박지영','김성호'],payers:['박*영','김*호'],dueDay:19,status:'active',payments:{'2026-08':{paidOn:'2026-08-19',amount:280000,method:'울산페이'}},messages:[],dueHistory:[]},
{id:'h2',name:'박윤아',students:['박윤아'],parents:['이정희'],payers:['이*희'],dueDay:2,status:'active',payments:{'2026-07':{paidOn:'2026-07-02',amount:145000,method:'카드'}},messages:[{sentOn:'2026-09-08'}],dueHistory:[]},
{id:'h3',name:'황찬규',students:['황찬규'],parents:['황정수'],payers:['황*수'],dueDay:23,status:'active',payments:{'2026-06':{paidOn:'2026-06-23',amount:165000,method:'계좌'}},messages:[],dueHistory:[]},
{id:'h4',name:'김태은',students:['김태은'],parents:[],payers:[],dueDay:28,status:'paused',extensionInProgress:true,payments:{},messages:[],dueHistory:[],note:'휴원 중 · 납부일 연장 진행 중'},
{id:'h5',name:'강민준',students:['강민준'],parents:[],payers:[],dueDay:null,status:'paused',payments:{},messages:[],dueHistory:[],note:'휴원 중'},
{id:'h6',name:'이준범',students:['이준범'],parents:[],payers:[],dueDay:null,status:'paused',payments:{},messages:[],dueHistory:[],note:'휴원 중'},
{id:'h7',name:'김예성 · 김예담',students:['김예성','김예담'],parents:[],payers:[],dueDay:null,status:'withdrawn',payments:{},messages:[],dueHistory:[],note:'퇴관 · 과거 회비자료 보존'},
{id:'h8',name:'윤유은 · 윤우진',students:['윤유은','윤우진'],parents:[],payers:[],dueDay:null,status:'withdrawn',payments:{},messages:[],dueHistory:[],note:'퇴관 · 과거 회비자료 보존'},
{id:'h9',name:'한정민 · 한지아',students:['한정민','한지아'],parents:[],payers:[],dueDay:null,status:'withdrawn',payments:{},messages:[],dueHistory:[],note:'퇴관 · 과거 회비자료 보존'},
{id:'h10',name:'이승재',students:['이승재'],parents:[],payers:[],dueDay:null,status:'withdrawn',payments:{},messages:[],dueHistory:[],note:'퇴관 · 과거 회비자료 보존'},
{id:'h11',name:'윤우준 · 윤이현',students:['윤우준','윤이현'],parents:[],payers:[],dueDay:30,status:'active',payments:{},messages:[],dueHistory:[]},
{id:'h12',name:'김우리 · 김나라 · 김사랑',students:['김우리','김나라','김사랑'],parents:[],payers:[],dueDay:15,status:'active',payments:{},messages:[],dueHistory:[],siblingDiscount:true},
{id:'h13',name:'이해찬 · 이정빈',students:['이해찬','이정빈'],parents:[],payers:[],dueDay:20,status:'active',payments:{},messages:[],dueHistory:[],siblingDiscount:true}
];
const state={households:demoHouseholds,filter:'all',sort:'due',query:'',paymentHouseholdId:null,dueHouseholdId:null,statusHouseholdId:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function ym(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function dueDateFor(m,d){if(!d)return null;const y=m.getFullYear(),mo=m.getMonth(),last=new Date(y,mo+1,0).getDate();return new Date(y,mo,Math.min(d,last),23,59,59)}
function overdueMonths(h){if(h.status!=='active'||!h.dueDay)return[];const a=[];for(let o=5;o>=0;o--){const m=new Date(today.getFullYear(),today.getMonth()-o,1),k=ym(m),due=dueDateFor(m,h.dueDay);if(due&&due<today&&!h.payments[k])a.push(k)}return a}
function daysAfterDue(h){if(!h.dueDay)return-999;return Math.floor((today-dueDateFor(new Date(today.getFullYear(),today.getMonth(),1),h.dueDay))/86400000)}
function statusOf(h){if(h.status==='paused')return{kind:'info',label:h.extensionInProgress?'휴원 · 연장중':'휴원'};if(h.status==='withdrawn')return{kind:'muted',label:'퇴관'};const m=overdueMonths(h);if(m.length)return{kind:'bad',label:`${m.length}회 미납`};const d=daysAfterDue(h);if(d>=0)return{kind:'late',label:'납부일 경과'};if(d>=-3)return{kind:'warn',label:'납부 임박'};return{kind:'ok',label:'정상'}}
function smsReady(h){if(h.status!=='active')return false;const m=overdueMonths(h);if(!m.length)return false;const due=dueDateFor(new Date(`${m[0]}-01T00:00:00`),h.dueDay);return Math.floor((today-due)/86400000)>=7}
function money(v){return new Intl.NumberFormat('ko-KR').format(v)+'원'}
function summary(){const active=state.households.filter(h=>h.status==='active'),c={ok:0,warn:0,late:0,bad:0};active.forEach(h=>{const k=statusOf(h).kind;if(c[k]!=null)c[k]++});$('#sumHouseholds').textContent=state.households.length+'가정';$('#sumActive').textContent=active.length+'가정';$('#sumOk').textContent=c.ok;$('#sumWarn').textContent=c.warn;$('#sumLate').textContent=c.late;$('#sumBad').textContent=c.bad;$('#sumSms').textContent=state.households.filter(smsReady).length;$('#sumBadNote').textContent=`1회 ${state.households.filter(h=>overdueMonths(h).length===1).length} · 2회 ${state.households.filter(h=>overdueMonths(h).length===2).length} · 3회+ ${state.households.filter(h=>overdueMonths(h).length>=3).length}`}
function match(h,q){if(!q)return true;return[h.name,...h.students,...h.parents,...h.payers,h.note||''].join(' ').replace(/\s/g,'').toLowerCase().includes(q.replace(/\s/g,'').toLowerCase())}
function filtered(){let r=state.households.filter(h=>match(h,state.query));if(['active','paused','withdrawn'].includes(state.filter))r=r.filter(h=>h.status===state.filter);if(state.filter==='bad')r=r.filter(h=>overdueMonths(h).length);if(state.filter==='sms')r=r.filter(smsReady);if(state.sort==='name')r.sort((a,b)=>a.name.localeCompare(b.name,'ko'));if(state.sort==='due')r.sort((a,b)=>(a.dueDay??99)-(b.dueDay??99)||a.name.localeCompare(b.name,'ko'));if(state.sort==='bad')r.sort((a,b)=>overdueMonths(b).length-overdueMonths(a).length);return r}
function renderRows(){const b=$('#householdRows');b.innerHTML='';filtered().forEach(h=>{const s=statusOf(h),r=document.createElement('div');r.className='row';const msg=smsReady(h)?'💬 문자대상':h.status==='paused'?'미납·문자 제외':h.status==='withdrawn'?'과거자료 보존':'-';r.innerHTML=`<div><strong>${h.name}</strong><div class="mini">${h.dueDay?`기준일 ${h.dueDay}일`:'기준일 확인필요'}${h.extensionInProgress?' · 연장 진행중':''}</div></div><span class="badge ${s.kind}">${s.label}</span><span>${msg}</span><button class="btn" data-open="${h.id}">상세</button>`;b.appendChild(r)});if(!filtered().length)b.innerHTML='<div class="mini">검색 결과가 없습니다.</div>'}
function openHousehold(id){const h=state.households.find(x=>x.id===id),s=statusOf(h),miss=overdueMonths(h);$('#modalTitle').textContent=h.name;const history=(h.dueHistory||[]).slice().reverse().map(x=>`<div class="mini">${x.changedOn} · ${x.oldDay||'-'}일 → ${x.newDay}일 · ${x.reason}${x.memo?' · '+x.memo:''}</div>`).join('')||'<div class="mini">변경이력 없음</div>';$('#modalBody').innerHTML=`<div class="detail-grid"><div><span>현재 상태</span><b class="badge ${s.kind}">${s.label}</b></div><div><span>기준 납부일</span><b>${h.dueDay?`매월 ${h.dueDay}일`:'확인 필요'}</b></div><div><span>보호자</span><b>${h.parents.join(', ')||'-'}</b></div><div><span>결제자</span><b>${h.payers.join(', ')||'-'}</b></div></div>${h.note?`<div class="detail-section"><strong>메모</strong><div>${h.note}</div></div>`:''}<div class="detail-section"><strong>미납 월</strong><div>${h.status==='active'?(miss.length?miss.map(x=>`<span class="month-chip bad">${Number(x.slice(5))}월</span>`).join(' '):'없음'):'현재 미납 계산 제외'}</div></div><div class="detail-section"><strong>납부일 변경이력</strong>${history}</div><div class="modal-actions"><button class="btn primary" id="openPay">💰 회비 받음</button><button class="btn" id="openDue">📅 납부일 변경</button><button class="btn" id="openStatus">🔄 상태 변경</button><button class="btn">💬 문자</button></div>`;$('#modal').hidden=false;$('#openPay').onclick=()=>openPayment(id);$('#openDue').onclick=()=>openDue(id);$('#openStatus').onclick=()=>openStatus(id)}
function openPayment(id){const h=state.households.find(x=>x.id===id);state.paymentHouseholdId=id;$('#modal').hidden=true;$('#paymentTitle').textContent=`💰 ${h.name} 회비 등록`;$('#billingMonth').value=ym(today);$('#paidOn').value='2026-09-10';$('#amount').value='';$('#paymentMethod').value='울산페이';$('#paymentMemo').value='';const miss=overdueMonths(h);$('#quickMonths').innerHTML=miss.length?miss.map(m=>`<button type="button" class="btn" data-month="${m}">${Number(m.slice(5))}월 미납</button>`).join(''):'<span class="mini">현재 미납월 없음</span>';$$('#quickMonths [data-month]').forEach(b=>b.onclick=()=>$('#billingMonth').value=b.dataset.month);$('#paymentModal').hidden=false}
function savePayment(e){e.preventDefault();const h=state.households.find(x=>x.id===state.paymentHouseholdId),m=$('#billingMonth').value,p=$('#paidOn').value,a=Number($('#amount').value),method=$('#paymentMethod').value;if(!m||!p||!a)return alert('적용월, 실제 납부일, 금액을 확인해 주세요.');h.payments[m]={paidOn:p,amount:a,method,memo:$('#paymentMemo').value.trim()};$('#paymentModal').hidden=true;state.paymentHouseholdId=null;refresh();alert(`${h.name} · ${Number(m.slice(5))}월분 ${money(a)} 등록\n※ 운영 DB에는 아직 저장되지 않았습니다.`)}
function openDue(id){const h=state.households.find(x=>x.id===id);state.dueHouseholdId=id;$('#modal').hidden=true;$('#dueTitle').textContent=`📅 ${h.name} 납부일 변경`;$('#newDueDay').value=h.dueDay||'';$('#dueReason').value=h.status==='paused'?'휴원':'여행';$('#dueMemo').value='';$('#dueModal').hidden=false}
function saveDue(e){e.preventDefault();const h=state.households.find(x=>x.id===state.dueHouseholdId),n=Number($('#newDueDay').value),reason=$('#dueReason').value;if(n<1||n>31)return;h.dueHistory=h.dueHistory||[];h.dueHistory.push({oldDay:h.dueDay,newDay:n,reason,memo:$('#dueMemo').value.trim(),changedOn:'2026-09-10'});h.dueDay=n;h.extensionInProgress=false;$('#dueModal').hidden=true;state.dueHouseholdId=null;refresh();openHousehold(h.id)}
function openStatus(id){const h=state.households.find(x=>x.id===id);state.statusHouseholdId=id;$('#modal').hidden=true;$('#statusTitle').textContent=`🔄 ${h.name} 상태 변경`;$('#statusMemo').value='';$('#statusModal').hidden=false}
function changeStatus(newStatus){const h=state.households.find(x=>x.id===state.statusHouseholdId);if(!h)return;h.status=newStatus;h.extensionInProgress=false;const memo=$('#statusMemo').value.trim();if(memo)h.note=memo;if(newStatus==='paused'&&!memo)h.note='휴원 중';if(newStatus==='withdrawn'&&!memo)h.note='퇴관 · 과거 회비자료 보존';if(newStatus==='active'&&!memo)h.note='';$('#statusModal').hidden=true;state.statusHouseholdId=null;refresh();openHousehold(h.id)}
function renderUlsan(){const q=$('#ulsanInput').value.trim(),o=$('#ulsanResult');if(!q){o.innerHTML='';return}const r=state.households.filter(h=>match(h,q));o.innerHTML=r.length?r.map(h=>`<button class="candidate" data-open="${h.id}"><strong>${h.name}</strong><span>${h.payers.join(', ')||'등록 결제자 없음'}</span></button>`).join(''):'<div class="mini">등록된 후보가 없습니다.</div>'}
function todayPayments(){const l=[];state.households.forEach(h=>Object.entries(h.payments).forEach(([month,p])=>{if(p.paidOn==='2026-09-10')l.push({h,month,...p})}));$('#todayTotal').textContent=`${l.length}가정 · ${money(l.reduce((a,b)=>a+b.amount,0))}`;$('#todayList').innerHTML=l.map(x=>`<p>${x.h.name} · ${Number(x.month.slice(5))}월분 · ${money(x.amount)} · ${x.method}</p>`).join('')||'<p class="mini">오늘 등록된 회비가 없습니다.</p>'}
function refresh(){summary();renderRows();todayPayments();$$('[data-filter]').forEach(b=>b.classList.toggle('active-filter',b.dataset.filter===state.filter))}
$('#searchInput').oninput=e=>{state.query=e.target.value;renderRows()};$('#ulsanInput').oninput=renderUlsan;$('#ulsanFind').onclick=renderUlsan;$$('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;refresh()});$$('[data-sort]').forEach(b=>b.onclick=()=>{state.sort=b.dataset.sort;renderRows()});document.addEventListener('click',e=>{const id=e.target.closest('[data-open]')?.dataset.open;if(id)openHousehold(id)});$('#modalClose').onclick=()=>$('#modal').hidden=true;$('#paymentClose').onclick=$('#paymentCancel').onclick=()=>$('#paymentModal').hidden=true;$('#paymentForm').onsubmit=savePayment;$('#dueClose').onclick=$('#dueCancel').onclick=()=>$('#dueModal').hidden=true;$('#dueForm').onsubmit=saveDue;$('#statusClose').onclick=()=>$('#statusModal').hidden=true;$$('[data-status-choice]').forEach(b=>b.onclick=()=>changeStatus(b.dataset.statusChoice));refresh();