package kr.com.taekwonkumdo.classsender;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.widget.*;import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    TextView status,account,server,today,last;Button toggle;boolean enabled;
    @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.statusText);account=findViewById(R.id.accountText);server=findViewById(R.id.serverText);today=findViewById(R.id.todayText);last=findViewById(R.id.lastText);toggle=findViewById(R.id.toggleButton);toggle.setOnClickListener(v->toggle());findViewById(R.id.batteryButton).setOnClickListener(v->battery());requestPermissions();refresh();new Handler(Looper.getMainLooper()).postDelayed(new Runnable(){public void run(){if(!isFinishing()){refreshLocal();new Handler(Looper.getMainLooper()).postDelayed(this,3000);}}},3000);}
    void requestPermissions(){if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.SEND_SMS,Manifest.permission.POST_NOTIFICATIONS},90);else requestPermissions(new String[]{Manifest.permission.SEND_SMS},90);}
    void refreshLocal(){enabled=getSharedPreferences("kmt_sender",MODE_PRIVATE).getBoolean("enabled",false);status.setText(enabled?"ON":"OFF");toggle.setText(enabled?"발신기 OFF":"발신기 ON");today.setText("오늘 발송: "+getSharedPreferences("kmt_sender",MODE_PRIVATE).getInt("today_count",0)+"건");last.setText("마지막 발송: "+getSharedPreferences("kmt_sender",MODE_PRIVATE).getString("last_sent","없음"));String state=getSharedPreferences("kmt_sender",MODE_PRIVATE).getString("server_state",null);if(state!=null&&enabled)server.setText(state);}
    void refresh(){refreshLocal();boolean sms=checkSelfPermission(Manifest.permission.SEND_SMS)==PackageManager.PERMISSION_GRANTED;toggle.setEnabled(sms);account.setText("로그인 없이 자동 연결");if(!sms){server.setText("SMS 권한을 허용해 주세요.");return;}Executors.newSingleThreadExecutor().execute(()->{try{new ApiClient(this).heartbeat(Settings.Secure.getString(getContentResolver(),Settings.Secure.ANDROID_ID),Build.MANUFACTURER+" "+Build.MODEL,enabled);runOnUiThread(()->server.setText("Supabase 연결 정상 · NO LOGIN"));}catch(Exception e){runOnUiThread(()->server.setText("연결 확인 필요: "+e.getMessage()));}});}
    void toggle(){if(enabled)stopSender();else startSender();refresh();}
    void startSender(){getSharedPreferences("kmt_sender",MODE_PRIVATE).edit().putBoolean("enabled",true).apply();Intent i=new Intent(this,SenderService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
    void stopSender(){getSharedPreferences("kmt_sender",MODE_PRIVATE).edit().putBoolean("enabled",false).apply();stopService(new Intent(this,SenderService.class));}
    void battery(){if(Build.VERSION.SDK_INT>=23)try{startActivity(new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}}
    @Override protected void onResume(){super.onResume();refresh();}
}
