package kr.com.taekwonkumdo.classsender;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.widget.*;import java.net.URLEncoder;import java.nio.charset.StandardCharsets;import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    TextView status,account,server,today,last;Button login,toggle;AuthStore auth;boolean enabled;
    @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.statusText);account=findViewById(R.id.accountText);server=findViewById(R.id.serverText);today=findViewById(R.id.todayText);last=findViewById(R.id.lastText);login=findViewById(R.id.loginButton);toggle=findViewById(R.id.toggleButton);auth=new AuthStore(this);capture(getIntent());login.setOnClickListener(v->login());toggle.setOnClickListener(v->toggle());findViewById(R.id.logoutButton).setOnClickListener(v->{stopSender();auth.clear();refresh();});findViewById(R.id.batteryButton).setOnClickListener(v->battery());requestPermissions();refresh();new Handler(Looper.getMainLooper()).postDelayed(new Runnable(){public void run(){if(!isFinishing()){refreshLocal();new Handler(Looper.getMainLooper()).postDelayed(this,3000);}}},3000);}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);capture(i);refresh();}
    void capture(Intent i){if(auth.capture(i.getData()))Toast.makeText(this,"Google 로그인이 완료되었습니다.",Toast.LENGTH_LONG).show();}
    void login(){try{String u=AppConfig.SUPABASE_URL+"/auth/v1/authorize?provider=google&redirect_to="+URLEncoder.encode(AppConfig.CALLBACK,"UTF-8")+"&prompt=select_account";startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){server.setText(e.getMessage());}}
    void requestPermissions(){if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.SEND_SMS,Manifest.permission.POST_NOTIFICATIONS},90);else requestPermissions(new String[]{Manifest.permission.SEND_SMS},90);}
    void refreshLocal(){enabled=getSharedPreferences("kmt_sender",MODE_PRIVATE).getBoolean("enabled",false);status.setText(enabled?"ON":"OFF");toggle.setText(enabled?"발신기 OFF":"발신기 ON");today.setText("오늘 발송: "+getSharedPreferences("kmt_sender",MODE_PRIVATE).getInt("today_count",0)+"건");last.setText("마지막 발송: "+getSharedPreferences("kmt_sender",MODE_PRIVATE).getString("last_sent","없음"));String state=getSharedPreferences("kmt_sender",MODE_PRIVATE).getString("server_state",null);if(state!=null&&enabled)server.setText(state);}
    void refresh(){refreshLocal();toggle.setEnabled(auth.hasSession()&&checkSelfPermission(Manifest.permission.SEND_SMS)==PackageManager.PERMISSION_GRANTED);account.setText(auth.hasSession()?"관리자 계정 확인 중...":"Google 관리자 로그인 필요");if(auth.hasSession())Executors.newSingleThreadExecutor().execute(()->{try{String email=new ApiClient(this).userEmail();runOnUiThread(()->{if(AppConfig.ADMIN_EMAIL.equalsIgnoreCase(email)){account.setText(email);server.setText("Supabase 연결 정상");}else{auth.clear();stopSender();account.setText("승인되지 않은 계정");}});}catch(Exception e){runOnUiThread(()->server.setText("연결 확인 필요: "+e.getMessage()));}});}
    void toggle(){if(enabled)stopSender();else startSender();refresh();}
    void startSender(){getSharedPreferences("kmt_sender",MODE_PRIVATE).edit().putBoolean("enabled",true).apply();Intent i=new Intent(this,SenderService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
    void stopSender(){getSharedPreferences("kmt_sender",MODE_PRIVATE).edit().putBoolean("enabled",false).apply();stopService(new Intent(this,SenderService.class));}
    void battery(){if(Build.VERSION.SDK_INT>=23)try{startActivity(new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}}
    @Override protected void onResume(){super.onResume();refresh();}
}
