package kr.com.taekwonkumdo.classsender;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.*;import android.provider.Settings;import android.telephony.SmsManager;import org.json.JSONObject;import java.util.ArrayList;import java.util.concurrent.*;

public class SenderService extends Service {
    static final String CHANNEL="kmt_sender_channel";ScheduledExecutorService timer;String deviceId;PowerManager.WakeLock wake;
    @Override public void onCreate(){super.onCreate();deviceId=Settings.Secure.getString(getContentResolver(),Settings.Secure.ANDROID_ID);createChannel();startForeground(901,notification("서버 연결 준비"));PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);wake=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"KMT:SmsPoll");timer=Executors.newSingleThreadScheduledExecutor();timer.scheduleWithFixedDelay(this::pollSafe,1,10,TimeUnit.SECONDS);}
    void pollSafe(){if(!getSharedPreferences("kmt_sender",MODE_PRIVATE).getBoolean("enabled",false)){stopSelf();return;}if(checkSelfPermission(Manifest.permission.SEND_SMS)!=PackageManager.PERMISSION_GRANTED){update("SMS 권한 필요");return;}wake.acquire(25000);try{if(!flushAck())return;ApiClient api=new ApiClient(this);api.heartbeat(deviceId,Build.MANUFACTURER+" "+Build.MODEL,true);JSONObject row=api.claim(deviceId);if(row==null){update("연결 정상 · 대기 문자 0건");return;}send(row);}catch(Exception e){update("연결 재시도 · "+shortText(e.getMessage()));}finally{if(wake.isHeld())wake.release();}}
    boolean flushAck(){android.content.SharedPreferences p=getSharedPreferences("kmt_sender",MODE_PRIVATE);String id=p.getString("ack_outbox",null);if(id==null)return true;try{new ApiClient(this).finish(id,p.getString("ack_device",deviceId),p.getBoolean("ack_success",false),p.getString("ack_error",null));p.edit().remove("ack_outbox").remove("ack_device").remove("ack_success").remove("ack_error").apply();return true;}catch(Exception e){update("발송결과 서버 전달 재시도");return false;}}
    void send(JSONObject row)throws Exception{String id=row.getString("id"),phone=row.getString("recipient_phone"),message=row.getString("message"),name=row.optString("student_name","원생");SmsManager sm=SmsManager.getDefault();ArrayList<String> parts=sm.divideMessage(message);ArrayList<PendingIntent> sent=new ArrayList<>();getSharedPreferences("kmt_sms_parts",MODE_PRIVATE).edit().putInt(id+"_ok",0).putInt(id+"_done",0).putBoolean(id+"_final",false).apply();for(int i=0;i<parts.size();i++){Intent x=new Intent(this,SmsResultReceiver.class).setAction("kr.com.taekwonkumdo.SMS_SENT").putExtra("outbox",id).putExtra("device",deviceId).putExtra("student",name).putExtra("part",i).putExtra("total",parts.size());sent.add(PendingIntent.getBroadcast(this,id.hashCode()+i,x,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));}sm.sendMultipartTextMessage(phone,null,parts,sent,null);update(name+" 문자 발송중");}
    void update(String text){NotificationManager n=getSystemService(NotificationManager.class);n.notify(901,notification(text));getSharedPreferences("kmt_sender",MODE_PRIVATE).edit().putString("server_state",text).apply();sendBroadcast(new Intent("kr.com.taekwonkumdo.SENDER_STATE").setPackage(getPackageName()));}
    Notification notification(String text){Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,CHANNEL).setSmallIcon(android.R.drawable.stat_notify_chat).setContentTitle("계명 CLASS 문자 발신기 ON").setContentText(text).setOngoing(true).setContentIntent(pi).build();}
    void createChannel(){if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel(CHANNEL,"문자 발신기",NotificationManager.IMPORTANCE_LOW));}
    String shortText(String s){if(s==null)return"오류";return s.length()>55?s.substring(0,55):s;}
    @Override public int onStartCommand(Intent i,int f,int id){return START_STICKY;}@Override public void onDestroy(){if(timer!=null)timer.shutdownNow();super.onDestroy();}@Override public android.os.IBinder onBind(Intent i){return null;}
}
