package kr.com.taekwonkumdo.classsender;

import android.app.Activity;import android.content.*;import android.telephony.SmsManager;import java.text.SimpleDateFormat;import java.util.*;import java.util.concurrent.Executors;

public class SmsResultReceiver extends BroadcastReceiver {
    @Override public void onReceive(Context c,Intent i){String id=i.getStringExtra("outbox"),device=i.getStringExtra("device"),student=i.getStringExtra("student");int total=i.getIntExtra("total",1),code=getResultCode();SharedPreferences p=c.getSharedPreferences("kmt_sms_parts",Context.MODE_PRIVATE);synchronized(SmsResultReceiver.class){if(p.getBoolean(id+"_final",false))return;int done=p.getInt(id+"_done",0)+1,ok=p.getInt(id+"_ok",0)+(code==Activity.RESULT_OK?1:0);p.edit().putInt(id+"_done",done).putInt(id+"_ok",ok).apply();if(code!=Activity.RESULT_OK||done>=total){boolean success=code==Activity.RESULT_OK&&ok>=total;String error=success?null:errorText(code);p.edit().putBoolean(id+"_final",true).apply();SharedPreferences main=c.getSharedPreferences("kmt_sender",Context.MODE_PRIVATE);SharedPreferences.Editor e=main.edit().putString("ack_outbox",id).putString("ack_device",device).putBoolean("ack_success",success).putString("ack_error",error);if(success){Calendar now=Calendar.getInstance();String day=new SimpleDateFormat("yyyyMMdd",Locale.KOREA).format(now.getTime()),old=main.getString("count_day","");int count=old.equals(day)?main.getInt("today_count",0)+1:1;e.putString("count_day",day).putInt("today_count",count).putString("last_sent",new SimpleDateFormat("HH:mm",Locale.KOREA).format(now.getTime())+" "+student);}e.apply();Executors.newSingleThreadExecutor().execute(()->{try{new ApiClient(c).finish(id,device,success,error);main.edit().remove("ack_outbox").remove("ack_device").remove("ack_success").remove("ack_error").apply();}catch(Exception ignored){}});}}
    }
    static String errorText(int c){switch(c){case SmsManager.RESULT_ERROR_NO_SERVICE:return"통신 서비스 없음";case SmsManager.RESULT_ERROR_RADIO_OFF:return"비행기모드 또는 통신 꺼짐";case SmsManager.RESULT_ERROR_LIMIT_EXCEEDED:return"통신사 발송 제한";case SmsManager.RESULT_ERROR_SHORT_CODE_NOT_ALLOWED:return"단축번호 발송 제한";default:return"SMS 발송 실패 코드 "+c;}}
}
