import{createClient}from"https://esm.sh/@supabase/supabase-js@2";const cfg=window.KMT_SMS_CONFIG,db=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,detectSessionInUrl:true,flowType:"pkce"}}),$=id=>document.getElementById(id),state={rows:[],settings:null,channel:null};
const clean=v=>v==null?"":String(v).trim(),esc=v=>clean(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])),labels={pending:"대기",sending:"발송중",sent:"완료",failed:"실패",cancelled:"취소"};function toast(m){$("toast").textContent=m;$("toast").classList.add("show");clearTimeout(window.__smsToast);window.__smsToast=setTimeout(()=>$("toast").classList.remove("show"),1800)}function fmt(v){return new Intl.DateTimeFormat("ko-KR",{timeZone:cfg.timezone,month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}function mask(v){const n=clean(v);return n.length>7?`${n.slice(0,3)}-****-${n.slice(-4)}`:"번호 확인"}
async function login(){const{error}=await db.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}${location.pathname}`,queryParams:{prompt:"select_account"}}});if(error)$("loginMessage").textContent=error.message}async function boot(){const{data:{session}}=await db.auth.getSession();if(!session){$("loginScreen").hidden=false;return}if(clean(session.user.email).toLowerCase()!==cfg.allowedAdminEmail.toLowerCase()){await db.auth.signOut();$("loginMessage").textContent="등록되지 않은 관리자 계정입니다.";return}$("loginScreen").hidden=true;$("app").hidden=false;await load();subscribe()}
async function load(){const[o,s,d]=await Promise.all([db.from("sms_outbox").select("id,student_id,recipient_name,recipient_phone,message,status,attempts,last_error,created_at,students(name,student_code)").order("created_at",{ascending:false}).limit(200),db.from("sms_settings").select("*").eq("id",1).single(),db.from("sms_sender_status").select("*").eq("id",1).single()]);const e=o.error||s.error||d.error;if(e){toast(e.message);return}state.rows=o.data||[];state.settings=s.data;$("attendanceEnabled").checked=s.data.attendance_enabled;$("messageTemplate").value=s.data.attendance_template;preview();render();const online=d.data?.is_enabled&&d.data.last_seen_at&&(Date.now()-new Date(d.data.last_seen_at).getTime()<120000);$("deviceStatus").textContent=online?"ON · 연결 정상":"연결 전";$("deviceSeen").textContent=d.data?.last_seen_at?`마지막 연결 ${fmt(d.data.last_seen_at)}`:"WORK9에서 연결"}
function render(){const counts={pending:0,sending:0,sent:0,failed:0};state.rows.forEach(r=>{if(counts[r.status]!=null)counts[r.status]++});Object.keys(counts).forEach(k=>$(`${k}Count`).textContent=counts[k]);const f=$("statusFilter").value,rows=state.rows.filter(r=>f==="all"||r.status===f);$("emptyQueue").hidden=rows.length>0;$("queueStatus").textContent=`최근 ${state.rows.length}건 · 실제 발송은 아직 중지`;$("queueList").innerHTML=rows.map(r=>`<article class="queue-row"><div><span class="status ${esc(r.status)}">${labels[r.status]||r.status}</span><small>${fmt(r.created_at)}</small></div><div><strong>${esc(r.students?.name||"원생")}</strong><small>${esc(r.students?.student_code||"")}</small></div><div class="message"><span>${esc(r.message)}</span><small>${esc(r.recipient_name||"보호자")} · ${mask(r.recipient_phone)}${r.last_error?` · ${esc(r.last_error)}`:""}</small></div><div><small>시도 ${r.attempts}회</small>${["failed","cancelled"].includes(r.status)?`<button class="retry" data-id="${r.id}">재전송 대기</button>`:""}</div></article>`).join("");$("queueList").querySelectorAll(".retry").forEach(b=>b.onclick=()=>retry(b.dataset.id))}
function preview(){const t=$("messageTemplate").value||"";$("messagePreview").textContent=t.replaceAll("{학생명}","김민준").replaceAll("{시간}","16시 32분")}
async function save(){const template=clean($("messageTemplate").value);if(!template||template.length>300){$("settingsMessage").textContent="문구는 1~300자로 입력해 주세요.";return}const{error}=await db.from("sms_settings").update({attendance_enabled:$("attendanceEnabled").checked,attendance_template:template}).eq("id",1);if(error){$("settingsMessage").textContent=error.message;return}$("settingsMessage").textContent="저장되었습니다.";toast("문자 설정 저장 완료")}
async function retry(id){const{error}=await db.rpc("kmt_retry_sms",{p_outbox_id:id});if(error){toast(error.message);return}toast("재전송 대기로 변경했습니다.");await load()}
function subscribe(){state.channel=db.channel("sms-outbox-v080").on("postgres_changes",{event:"*",schema:"public",table:"sms_outbox"},()=>load()).on("postgres_changes",{event:"*",schema:"public",table:"sms_sender_status"},()=>load()).subscribe()}
$("loginButton").onclick=login;$("logoutButton").onclick=async()=>{await db.auth.signOut();location.reload()};$("refreshButton").onclick=load;$("statusFilter").onchange=render;$("messageTemplate").oninput=preview;$("saveSettings").onclick=save;db.auth.onAuthStateChange((_e,s)=>{if(s&&$("app").hidden)setTimeout(boot,0)});boot();
