import{createClient}from"https://esm.sh/@supabase/supabase-js@2";const cfg=window.KMT_SPARK_GROUP_CONFIG,db=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,detectSessionInUrl:true,flowType:"pkce"}}),$=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),fmt=v=>Number(v||0).toLocaleString("ko-KR");function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul"}).format(new Date())}function toast(v){$("toast").textContent=v;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}

const SINGLE_OWNER_EMAIL="jeonseongkweon@gmail.com";
const isSingleOwner=session=>String(session?.user?.email||"").trim().toLowerCase()===SINGLE_OWNER_EMAIL;
async function login(){const{error}=await db.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}${location.pathname}`,queryParams:{prompt:"select_account"}}});if(error)$("loginMessage").textContent=error.message}
let booting=false;
async function boot(){if(booting)return;booting=true;try{const{data:{session},error}=await db.auth.getSession();if(error){$("loginMessage").textContent=`로그인 확인 오류: ${error.message}`;$("loginScreen").hidden=false;$("app").hidden=true;return}if(!session){$("loginScreen").hidden=false;$("app").hidden=true;return}if(!isSingleOwner(session)){$("loginMessage").textContent="이 화면을 사용할 지도자 권한이 없습니다.";return}history.replaceState({},document.title,location.pathname);$("loginScreen").hidden=true;$("app").hidden=false;$("missionStart").value=today();await loadDashboard()}finally{booting=false}}
async function loadDashboard(){const{data,error}=await db.rpc("kmt_get_spark_group_dashboard");if(error){toast(error.message);return}const g=data.group||{},s=data.stats||{};$("groupCode").textContent=g.code||"KMT-CLASS-001";$("groupName").textContent=g.name||"계명태권도";$("groupDescription").textContent=`${g.region||""} · ${g.description||""}`;[["statMembers",s.members],["statToday",s.today_participants],["statWeek",s.week_activities],["statSpark",fmt(s.total_spark)],["statFriend",s.friend_activities],["statFamily",s.family_activities],["statFilial",s.filial_activities],["statJoint",s.joint_missions],["statBadges",s.badges]].forEach(([id,v])=>$(id).textContent=v||0);renderRanking(data.ranking||[]);renderMissions(data.missions||[]);renderNews(data.news||[])}
function renderRanking(rows){$("ranking").innerHTML=rows.map((r,i)=>`<div class="rank-row"><b>${i+1}</b>${r.photo_url?`<img src="${esc(r.photo_url)}" alt="">`:'<span class="avatar"></span>'}<div><strong>${esc(r.name)}</strong><small>${esc(r.tier_icon||"")} ${esc(r.tier_name||"SPARK 준비")}</small></div><em>${fmt(r.spark)} SPARK</em></div>`).join("")||'<div class="empty">확인 완료된 SPARK 연결 대원을 기다리고 있습니다.</div>'}
function renderMissions(rows){$("missions").innerHTML=rows.map(r=>`<article class="mission"><strong>🌱 ${esc(r.title)}</strong><span>${esc(r.description||"함께 실천하는 계명태권도 공동미션")}</span><span>${esc(r.starts_on)} ~ ${esc(r.ends_on||"계속")}</span></article>`).join("")||'<div class="empty">등록된 그룹 공동미션이 없습니다.</div>'}
function renderNews(rows){$("news").innerHTML=rows.map(n=>`<article><strong>🔥 ${esc(n.title)}</strong><span>${esc(n.summary)}</span><time>${new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",dateStyle:"medium"}).format(new Date(n.published_at))}</time></article>`).join("")||'<div class="empty">등록된 SPARK NEWS가 없습니다.</div>'}
async function createMission(e){e.preventDefault();$("missionMessage").textContent="저장 중...";const{error}=await db.rpc("kmt_create_spark_group_mission",{p_title:$("missionTitle").value,p_description:$("missionDescription").value||null,p_starts_on:$("missionStart").value,p_ends_on:$("missionEnd").value||null});if(error){$("missionMessage").textContent=error.message;return}$("missionDialog").close();e.target.reset();$("missionStart").value=today();toast("공동미션을 등록했습니다.");await loadDashboard()}
async function createNews(e){e.preventDefault();$("newsMessage").textContent="저장 중...";const{error}=await db.rpc("kmt_create_spark_group_news",{p_title:$("newsTitle").value,p_summary:$("newsSummary").value});if(error){$("newsMessage").textContent=error.message;return}$("newsDialog").close();e.target.reset();toast("SPARK NEWS를 등록했습니다.");await loadDashboard()}
$("loginButton").onclick=login;$("logoutButton").onclick=async()=>{await db.auth.signOut();location.reload()};$("refreshButton").onclick=loadDashboard;document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>$(b.dataset.open).showModal());document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());$("missionForm").onsubmit=createMission;$("newsForm").onsubmit=createNews;db.auth.onAuthStateChange((_e,s)=>{if(s&&$("app").hidden)setTimeout(boot,0)});boot();
