-- 계명태권도 CLASS SYSTEM v1.1.0 / WORK11
create table if not exists public.spark_member_links(id uuid primary key default gen_random_uuid(),student_id uuid not null unique references public.students(id) on delete cascade,spark_user_id text not null unique check(length(btrim(spark_user_id)) between 3 and 120),spark_display_name text,link_status text not null default 'pending' check(link_status in('pending','verified','suspended')),linked_at timestamptz not null default timezone('utc',now()),linked_by uuid references auth.users(id) on delete set null default auth.uid(),verified_at timestamptz,updated_at timestamptz not null default timezone('utc',now()));
create table if not exists public.spark_member_link_audit(id bigint generated always as identity primary key,student_id uuid not null,student_code_snapshot text not null,student_name_snapshot text not null,spark_user_id text not null,action text not null check(action in('linked','updated','unlinked')),link_status text,acted_at timestamptz not null default timezone('utc',now()),acted_by uuid references auth.users(id) on delete set null default auth.uid());
create index if not exists spark_member_link_audit_student_idx on public.spark_member_link_audit(student_id,acted_at desc);
alter table public.spark_member_links enable row level security; alter table public.spark_member_link_audit enable row level security;
drop policy if exists spark_member_links_admin_all on public.spark_member_links; create policy spark_member_links_admin_all on public.spark_member_links for all to authenticated using(public.kmt_is_admin()) with check(public.kmt_is_admin());
drop policy if exists spark_member_link_audit_admin_read on public.spark_member_link_audit; create policy spark_member_link_audit_admin_read on public.spark_member_link_audit for select to authenticated using(public.kmt_is_admin());
grant select,insert,update,delete on public.spark_member_links to authenticated; grant select on public.spark_member_link_audit to authenticated;
drop trigger if exists spark_member_links_set_updated_at on public.spark_member_links; create trigger spark_member_links_set_updated_at before update on public.spark_member_links for each row execute function public.kmt_set_updated_at();
create or replace function public.kmt_link_spark_member(p_student_id uuid,p_confirm_student_code text,p_spark_user_id text,p_spark_display_name text default null,p_link_status text default 'pending') returns public.spark_member_links language plpgsql security definer set search_path=public,pg_temp as $$ declare v_student public.students%rowtype;v_link public.spark_member_links%rowtype;v_action text; begin if not public.kmt_is_admin() then raise exception '관리자 권한이 필요합니다.';end if;select * into strict v_student from public.students where id=p_student_id for update;if upper(btrim(coalesce(p_confirm_student_code,'')))<>upper(v_student.student_code) then raise exception 'KM번호 확인값이 선택한 학생과 일치하지 않습니다.';end if;if btrim(coalesce(p_spark_user_id,''))='' then raise exception 'SPARK 고유 ID를 입력해 주세요.';end if;if p_link_status not in('pending','verified','suspended') then raise exception '허용되지 않은 연결상태입니다.';end if;if exists(select 1 from public.spark_member_links where spark_user_id=btrim(p_spark_user_id) and student_id<>p_student_id) then raise exception '이 SPARK ID는 다른 CLASS 학생에게 이미 연결되어 있습니다.';end if;v_action:=case when exists(select 1 from public.spark_member_links where student_id=p_student_id) then 'updated' else 'linked' end;insert into public.spark_member_links(student_id,spark_user_id,spark_display_name,link_status,verified_at) values(p_student_id,btrim(p_spark_user_id),nullif(btrim(coalesce(p_spark_display_name,'')),''),p_link_status,case when p_link_status='verified' then timezone('utc',now()) end) on conflict(student_id) do update set spark_user_id=excluded.spark_user_id,spark_display_name=excluded.spark_display_name,link_status=excluded.link_status,verified_at=case when excluded.link_status='verified' then coalesce(spark_member_links.verified_at,timezone('utc',now())) else null end,linked_by=auth.uid() returning * into v_link;insert into public.spark_member_link_audit(student_id,student_code_snapshot,student_name_snapshot,spark_user_id,action,link_status) values(v_student.id,v_student.student_code,v_student.name,v_link.spark_user_id,v_action,v_link.link_status);return v_link;end;$$;
create or replace function public.kmt_unlink_spark_member(p_student_id uuid,p_confirm_student_code text) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ declare v_student public.students%rowtype;v_link public.spark_member_links%rowtype; begin if not public.kmt_is_admin() then raise exception '관리자 권한이 필요합니다.';end if;select * into strict v_student from public.students where id=p_student_id for update;if upper(btrim(coalesce(p_confirm_student_code,'')))<>upper(v_student.student_code) then raise exception 'KM번호 확인값이 선택한 학생과 일치하지 않습니다.';end if;delete from public.spark_member_links where student_id=p_student_id returning * into v_link;if not found then return false;end if;insert into public.spark_member_link_audit(student_id,student_code_snapshot,student_name_snapshot,spark_user_id,action,link_status) values(v_student.id,v_student.student_code,v_student.name,v_link.spark_user_id,'unlinked',v_link.link_status);return true;end;$$;
revoke all on function public.kmt_link_spark_member(uuid,text,text,text,text) from public;revoke all on function public.kmt_unlink_spark_member(uuid,text) from public;grant execute on function public.kmt_link_spark_member(uuid,text,text,text,text) to authenticated;grant execute on function public.kmt_unlink_spark_member(uuid,text) to authenticated;
select 'spark_member_links' check_name,count(*)::text result from public.spark_member_links union all select 'duplicate_student_links',count(*)::text from(select student_id from public.spark_member_links group by student_id having count(*)>1)x union all select 'duplicate_spark_ids',count(*)::text from(select spark_user_id from public.spark_member_links group by spark_user_id having count(*)>1)x;
