-- 계명태권도 CLASS SYSTEM v0.8.0
-- WORK8: Android 발신기 연결 전 문자 발송대기 서버 구조

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='guardians' and column_name='sms_enabled'
  ) then
    alter table public.guardians add column sms_enabled boolean not null default false;
    update public.guardians set sms_enabled=true
    where is_primary=true
      and nullif(regexp_replace(coalesce(phone,''), '[^0-9]', '', 'g'), '') is not null;
  end if;
end $$;

create table if not exists public.sms_settings (
  id smallint primary key default 1 check (id = 1),
  attendance_enabled boolean not null default true,
  attendance_template text not null default '{학생명} 학생이 {시간} 계명태권도에 도착했습니다.',
  sender_label text not null default '계명태권도',
  updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_at timestamptz not null default timezone('utc', now())
);

insert into public.sms_settings (id) values (1) on conflict (id) do nothing;

create table if not exists public.sms_outbox (
  id uuid primary key default gen_random_uuid(),
  attendance_id uuid not null references public.attendance(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete restrict,
  guardian_id uuid not null references public.guardians(id) on delete restrict,
  recipient_name text,
  recipient_phone text not null,
  message text not null,
  status text not null default 'pending' check (status in ('pending','sending','sent','failed','cancelled')),
  attempts smallint not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (attendance_id, guardian_id)
);

create table if not exists public.sms_logs (
  id bigint generated by default as identity primary key,
  outbox_id uuid not null references public.sms_outbox(id) on delete cascade,
  from_status text,
  to_status text not null,
  result_message text,
  device_id text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sms_sender_status (
  id smallint primary key default 1 check (id = 1),
  device_id text,
  device_name text,
  is_enabled boolean not null default false,
  last_seen_at timestamptz,
  last_sent_at timestamptz,
  app_version text,
  updated_at timestamptz not null default timezone('utc', now())
);

insert into public.sms_sender_status (id) values (1) on conflict (id) do nothing;

create index if not exists sms_outbox_status_idx on public.sms_outbox (status, next_attempt_at, created_at);
create index if not exists sms_outbox_student_idx on public.sms_outbox (student_id, created_at desc);
create index if not exists sms_logs_outbox_idx on public.sms_logs (outbox_id, created_at desc);

alter table public.sms_settings enable row level security;
alter table public.sms_outbox enable row level security;
alter table public.sms_logs enable row level security;
alter table public.sms_sender_status enable row level security;

drop policy if exists sms_settings_admin_all on public.sms_settings;
create policy sms_settings_admin_all on public.sms_settings for all to authenticated
using (public.kmt_is_admin()) with check (public.kmt_is_admin());
drop policy if exists sms_outbox_admin_all on public.sms_outbox;
create policy sms_outbox_admin_all on public.sms_outbox for all to authenticated
using (public.kmt_is_admin()) with check (public.kmt_is_admin());
drop policy if exists sms_logs_admin_all on public.sms_logs;
create policy sms_logs_admin_all on public.sms_logs for all to authenticated
using (public.kmt_is_admin()) with check (public.kmt_is_admin());
drop policy if exists sms_sender_status_admin_all on public.sms_sender_status;
create policy sms_sender_status_admin_all on public.sms_sender_status for all to authenticated
using (public.kmt_is_admin()) with check (public.kmt_is_admin());

grant select, update on public.sms_settings to authenticated;
grant select, insert, update on public.sms_outbox to authenticated;
grant select, insert on public.sms_logs to authenticated;
grant select, insert, update on public.sms_sender_status to authenticated;

drop trigger if exists sms_settings_set_updated_at on public.sms_settings;
create trigger sms_settings_set_updated_at before update on public.sms_settings
for each row execute function public.kmt_set_updated_at();
drop trigger if exists sms_outbox_set_updated_at on public.sms_outbox;
create trigger sms_outbox_set_updated_at before update on public.sms_outbox
for each row execute function public.kmt_set_updated_at();

create or replace function public.kmt_log_sms_status()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if tg_op='INSERT' or old.status is distinct from new.status then
    insert into public.sms_logs(outbox_id,from_status,to_status,result_message,device_id)
    values(new.id,case when tg_op='UPDATE' then old.status else null end,new.status,new.last_error,new.locked_by);
  end if;
  return new;
end;
$$;

drop trigger if exists sms_outbox_log_status on public.sms_outbox;
create trigger sms_outbox_log_status after insert or update of status on public.sms_outbox
for each row execute function public.kmt_log_sms_status();

create or replace function public.kmt_render_attendance_sms(p_student_name text, p_checked_at timestamptz)
returns text language plpgsql stable security invoker set search_path = public as $$
declare v_template text;
begin
  select attendance_template into v_template from public.sms_settings where id = 1;
  return replace(replace(coalesce(v_template, '{학생명} 학생이 {시간} 계명태권도에 도착했습니다.'),
    '{학생명}', coalesce(p_student_name, '원생')),
    '{시간}', to_char(timezone('Asia/Seoul', p_checked_at), 'HH24시 MI분'));
end;
$$;

create or replace function public.kmt_queue_attendance_sms()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_student_name text; v_guardian record; v_message text; v_enabled boolean;
begin
  if new.student_id is null then return new; end if;

  if new.status not in ('present','late') then
    update public.sms_outbox set status='cancelled', last_error='출석 상태 변경으로 취소'
    where attendance_id=new.id and status in ('pending','failed');
    return new;
  end if;

  select attendance_enabled into v_enabled from public.sms_settings where id=1;
  if coalesce(v_enabled, false) = false then return new; end if;
  select name into v_student_name from public.students where id=new.student_id;
  v_message := public.kmt_render_attendance_sms(v_student_name, new.checked_at);

  for v_guardian in
    select id, name, regexp_replace(coalesce(phone,''), '[^0-9]', '', 'g') as phone
    from public.guardians
    where student_id=new.student_id and sms_enabled=true
  loop
    if length(v_guardian.phone) between 10 and 11 then
      insert into public.sms_outbox(attendance_id,student_id,guardian_id,recipient_name,recipient_phone,message)
      values(new.id,new.student_id,v_guardian.id,v_guardian.name,v_guardian.phone,v_message)
      on conflict(attendance_id,guardian_id) do update set
        recipient_name=excluded.recipient_name,
        recipient_phone=excluded.recipient_phone,
        message=excluded.message,
        status=case when public.sms_outbox.status in ('failed','cancelled') then 'pending' else public.sms_outbox.status end,
        next_attempt_at=case when public.sms_outbox.status in ('failed','cancelled') then now() else public.sms_outbox.next_attempt_at end,
        last_error=case when public.sms_outbox.status in ('failed','cancelled') then null else public.sms_outbox.last_error end;
    end if;
  end loop;
  return new;
exception when others then
  -- 문자 대기 생성 오류가 출석 저장을 막지 않도록 완전히 분리한다.
  raise warning 'KMT SMS queue error for attendance %: %', new.id, sqlerrm;
  return new;
end;
$$;

drop trigger if exists attendance_queue_sms on public.attendance;
create trigger attendance_queue_sms after insert or update of status, checked_at on public.attendance
for each row execute function public.kmt_queue_attendance_sms();

create or replace function public.kmt_retry_sms(p_outbox_id uuid)
returns public.sms_outbox language plpgsql security invoker set search_path=public as $$
declare v_row public.sms_outbox;
begin
  if not public.kmt_is_admin() then raise exception '관리자 권한이 필요합니다.'; end if;
  update public.sms_outbox set status='pending',next_attempt_at=now(),locked_at=null,locked_by=null,last_error=null
  where id=p_outbox_id and status in ('failed','cancelled') returning * into v_row;
  return v_row;
end;
$$;

revoke all on function public.kmt_retry_sms(uuid) from public;
grant execute on function public.kmt_retry_sms(uuid) to authenticated;

select 'sms_outbox_ready' as check_name, count(*)::text as result from public.sms_outbox
union all select 'sms_logs_ready', count(*)::text from public.sms_logs
union all select 'sms_enabled_guardians', count(*)::text from public.guardians where sms_enabled;
