import{createClient}from"https://esm.sh/@supabase/supabase-js@2";const cfg=window.KMT_SPARK_TOGETHER_CONFIG,db=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,detectSessionInUrl:true,flowType:"pkce"}}),$=id=>document.getElementById(id),state={students:[],selected:null};

const SINGLE_OWNER_EMAIL="class-admin@ipma.kr";
const isSingleOwner=session=>String(session?.user?.email||"").trim().toLowerCase()===SINGLE_OWNER_EMAIL;
const labels={exercise:"운동하기",challenge:"새로운 도전",learning:"학습하기",habit:"좋은 생활습관",service:"봉사하기",public_good:"공익활동",greeting:"부모님께 먼저 인사",organizing:"신발·물건 정리",housework:"집안일 돕기",massage:"부모님 안마",gratitude:"감사 표현",help_first:"말씀 전 먼저 돕기",family_exercise:"가족과 운동",praise_friend:"친구 칭찬",approach_friend:"혼자 있는 친구에게 말 걸기",help_friend:"친구 돕기",friend_exercise:"친구와 운동",joint_mission:"친구와 공동미션",friend_service:"친구와 봉사",spark_intro:"친구에게 SPARK 소개",spark_together:"친구와 SPARK 함께하기"};
const options={personal:["exercise","challenge","learning","habit","service","public_good"],family:["greeting","organizing","housework","massage","gratitude","help_first","family_exercise"],friend:["praise_friend","approach_friend","help_friend","friend_exercise","joint_mission","friend_service","spark_intro","spark_together"]};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));function toast(v){$("toast").textContent=v;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul"}).format(new Date())}
async function login(){location.replace("../");}const{data,error}=await db.rpc("kmt_get_spark_together_history",{p_student_id:state.selected.student_id,p_limit:30});if(error){$("history").innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}$("history").innerHTML=(data||[]).map(a=>`<article><small>${esc(a.activity_date)}</small><strong>${a.axis==="personal"?"🌱 나의 성장":a.axis==="family"?"❤️ 가족":"🤝 친구"}</strong><span>${esc(labels[a.activity_code]||a.activity_code)}${a.partner_label?` · ${esc(a.partner_label)}`:""}${a.note?`<small> · ${esc(a.note)}</small>`:""}</span>${a.status==="verified"?`<button data-void="${a.id}">취소</button>`:"<small>취소됨</small>"}</article>`).join("")||'<div class="empty">아직 기록된 활동이 없습니다.</div>';document.querySelectorAll("[data-void]").forEach(b=>b.onclick=()=>voidActivity(b.dataset.void))}
async function saveActivity(e){e.preventDefault();if(!state.selected?.linked)return;$("formMessage").textContent="저장 중...";const axis=document.querySelector('[name="axis"]:checked').value,payload={p_student_id:state.selected.student_id,p_axis:axis,p_activity_code:$("activityCode").value,p_partner_student_id:axis==="friend"?($("partnerStudent").value||null):null,p_partner_label:$("partnerLabel").value||null,p_note:$("activityNote").value||null,p_activity_date:$("activityDate").value,p_idempotency_key:crypto.randomUUID()};const{error}=await db.rpc("kmt_record_spark_together",payload);if(error){$("formMessage").textContent=error.message;return}$("formMessage").textContent="";$("activityNote").value="";$("partnerLabel").value="";toast("함께하는 SPARK를 저장했습니다.");await loadRoster()}
async function voidActivity(id){if(!confirm("이 활동기록을 취소할까요? 기록은 감사이력에 보존됩니다."))return;const{error}=await db.rpc("kmt_void_spark_together",{p_activity_id:id});if(error){toast(error.message);return}toast("활동을 취소했습니다.");await loadRoster()}
$("loginButton").onclick=login;$("logoutButton").onclick=async()=>{await db.auth.signOut();location.reload()};$("studentSelect").onchange=async e=>{state.selected=state.students.find(s=>s.student_id===e.target.value);renderProfile();await loadHistory()};document.querySelectorAll('[name="axis"]').forEach(r=>r.onchange=renderActivityOptions);$("activityForm").onsubmit=saveActivity;$("refreshButton").onclick=loadRoster;renderActivityOptions();db.auth.onAuthStateChange((_e,s)=>{if(s&&$("app").hidden)setTimeout(boot,0)});boot();
