import{db,$,clean,escapeHtml,requireSession}from"../shared/core.js";
const state={menus:[],contents:[]};const split=v=>clean(v).split(",").map(x=>x.trim()).filter(Boolean);
async function load(){const[{data:menus,error:me},{data:contents,error:ce}]=await Promise.all([db.from("ai_office_menus").select("*").order("sort_order"),db.from("ai_office_contents").select("*").order("sort_order")]);if(me||ce)throw me||ce;state.menus=menus||[];state.contents=contents||[];render()}
function render(){$("menuId").innerHTML=state.menus.filter(x=>x.is_visible).map(x=>`<option value="${x.id}">${escapeHtml(x.title)}</option>`).join("");$("menuRows").innerHTML=state.menus.map(m=>`<div class="row"><b>${m.sort_order}</b><div><strong>${escapeHtml(m.title)}</strong><small>${m.is_visible?"공개":"숨김"}</small></div><button class="link-button" data-menu-edit="${m.id}">수정</button><button class="link-button" data-menu-toggle="${m.id}">${m.is_visible?"숨김":"공개"}</button><span></span></div>`).join("");$("contentRows").innerHTML=state.contents.map(c=>`<div class="row"><b>${c.sort_order}</b><div><strong>${escapeHtml(c.title)}</strong><small>${c.content_type} · ${state.menus.find(m=>m.id===c.menu_id)?.title||"메뉴 없음"} · ${c.is_visible?"공개":"숨김"}</small></div><button class="link-button" data-edit="${c.id}">수정</button><button class="link-button" data-toggle="${c.id}">${c.is_visible?"숨김":"공개"}</button><button class="danger" data-delete="${c.id}">삭제</button></div>`).join("");document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editContent(b.dataset.edit));document.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=()=>toggleContent(b.dataset.toggle));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteContent(b.dataset.delete));document.querySelectorAll("[data-menu-edit]").forEach(b=>b.onclick=()=>editMenu(b.dataset.menuEdit));document.querySelectorAll("[data-menu-toggle]").forEach(b=>b.onclick=()=>toggleMenu(b.dataset.menuToggle))}
function reset(){$("contentForm").reset();$("contentId").value="";$("sortOrder").value="100";$("visible").checked=true;$("formMessage").textContent=""}
function editContent(id){const c=state.contents.find(x=>x.id===id);if(!c)return;$("contentId").value=c.id;$("title").value=c.title;$("buttonLabel").value=c.button_label||"";$("menuId").value=c.menu_id;$("contentType").value=c.content_type;$("sourceUrl").value=c.source_url||"";$("voiceCommand").value=c.voice_command||"";$("voiceAliases").value=(c.voice_aliases||[]).join(", ");$("keywords").value=(c.keywords||[]).join(", ");$("sortOrder").value=c.sort_order;$("transition").value=c.transition;$("soundEffect").value=c.sound_effect;$("backgroundTheme").value=c.background_theme;$("webEmbed").value=String(c.web_embed_allowed!==false);$("favorite").checked=c.is_favorite;$("visible").checked=c.is_visible;scrollTo({top:0,behavior:"smooth"})}
async function upload(file){const ext=(file.name.split(".").pop()||"bin").toLowerCase();const path=`${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.${ext}`;const{error}=await db.storage.from("ai-office-media").upload(path,file,{cacheControl:"3600",upsert:false});if(error)throw error;return db.storage.from("ai-office-media").getPublicUrl(path).data.publicUrl}
$("contentForm").onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$("formMessage").textContent="저장 중…";try{let url=clean($("sourceUrl").value);const file=$("mediaFile").files[0];if(file)url=await upload(file);const row={title:clean($("title").value),button_label:clean($("buttonLabel").value)||clean($("title").value),menu_id:$("menuId").value,content_type:$("contentType").value,source_url:url||null,voice_command:clean($("voiceCommand").value)||null,voice_aliases:split($("voiceAliases").value),keywords:split($("keywords").value),sort_order:Number($("sortOrder").value)||100,transition:$("transition").value,sound_effect:$("soundEffect").value,background_theme:$("backgroundTheme").value,web_embed_allowed:$("webEmbed").value==="true",is_favorite:$("favorite").checked,is_visible:$("visible").checked};const id=$("contentId").value;const{error}=id?await db.from("ai_office_contents").update(row).eq("id",id):await db.from("ai_office_contents").insert(row);if(error)throw error;reset();await load();$("formMessage").textContent="✓ 저장했습니다."}catch(err){$("formMessage").textContent=`저장 실패: ${err.message}`}finally{button.disabled=false}}
async function toggleContent(id){const c=state.contents.find(x=>x.id===id);const{error}=await db.from("ai_office_contents").update({is_visible:!c.is_visible}).eq("id",id);if(error)alert(error.message);else load()}
async function deleteContent(id){if(!confirm("이 자료를 삭제할까요? 복구할 수 없습니다."))return;const{error}=await db.from("ai_office_contents").delete().eq("id",id);if(error)alert(error.message);else load()}
async function addMenu(existing){const title=prompt("메뉴 이름",existing?.title||"");if(!clean(title))return;const order=Number(prompt("표시 순서",String(existing?.sort_order||100)))||100;const candidates=state.menus.filter(m=>m.id!==existing?.id&&!m.parent_id);const guide=["0. 상위메뉴",...candidates.map((m,i)=>`${i+1}. ${m.title}`)].join("\n");const currentParent=existing?.parent_id?candidates.findIndex(m=>m.id===existing.parent_id)+1:0;const parentNumber=Number(prompt(`메뉴 위치를 선택하세요.\n${guide}`,String(Math.max(0,currentParent))))||0;const parent_id=parentNumber>0?candidates[parentNumber-1]?.id||null:null;const row={title:clean(title),sort_order:order,parent_id};const query=existing?db.from("ai_office_menus").update(row).eq("id",existing.id):db.from("ai_office_menus").insert(row);const{error}=await query;if(error)alert(error.message);else load()}
function editMenu(id){addMenu(state.menus.find(x=>x.id===id))}async function toggleMenu(id){const m=state.menus.find(x=>x.id===id);const{error}=await db.from("ai_office_menus").update({is_visible:!m.is_visible}).eq("id",id);if(error)alert(error.message);else load()}
$("resetForm").onclick=reset;$("addMenu").onclick=()=>addMenu();(async()=>{if(!await requireSession("../"))return;try{await load()}catch(e){$("formMessage").textContent=`설치 SQL을 확인해 주세요: ${e.message}`}})();
